/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as TradingJournalsRouteImport } from './routes/trading/journals'
import { Route as TradingTintoRouteImport } from './routes/trading/Tinto'
import { Route as OrjiBlogAdminRouteImport } from './routes/orji/blogAdmin'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiSendEmailRouteImport } from './routes/api/send-email'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradingJournalsRoute = TradingJournalsRouteImport.update({
  id: '/trading/journals',
  path: '/trading/journals',
  getParentRoute: () => rootRouteImport,
} as any)
const TradingTintoRoute = TradingTintoRouteImport.update({
  id: '/trading/Tinto',
  path: '/trading/Tinto',
  getParentRoute: () => rootRouteImport,
} as any)
const OrjiBlogAdminRoute = OrjiBlogAdminRouteImport.update({
  id: '/orji/blogAdmin',
  path: '/orji/blogAdmin',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendEmailRoute = ApiSendEmailRouteImport.update({
  id: '/api/send-email',
  path: '/api/send-email',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/api/send-email': typeof ApiSendEmailRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/orji/blogAdmin': typeof OrjiBlogAdminRoute
  '/trading/Tinto': typeof TradingTintoRoute
  '/trading/journals': typeof TradingJournalsRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/api/send-email': typeof ApiSendEmailRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/orji/blogAdmin': typeof OrjiBlogAdminRoute
  '/trading/Tinto': typeof TradingTintoRoute
  '/trading/journals': typeof TradingJournalsRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/api/send-email': typeof ApiSendEmailRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/orji/blogAdmin': typeof OrjiBlogAdminRoute
  '/trading/Tinto': typeof TradingTintoRoute
  '/trading/journals': typeof TradingJournalsRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/api/send-email'
    | '/blog/$slug'
    | '/orji/blogAdmin'
    | '/trading/Tinto'
    | '/trading/journals'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/api/send-email'
    | '/blog/$slug'
    | '/orji/blogAdmin'
    | '/trading/Tinto'
    | '/trading/journals'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/api/send-email'
    | '/blog/$slug'
    | '/orji/blogAdmin'
    | '/trading/Tinto'
    | '/trading/journals'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ApiSendEmailRoute: typeof ApiSendEmailRoute
  BlogSlugRoute: typeof BlogSlugRoute
  OrjiBlogAdminRoute: typeof OrjiBlogAdminRoute
  TradingTintoRoute: typeof TradingTintoRoute
  TradingJournalsRoute: typeof TradingJournalsRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trading/journals': {
      id: '/trading/journals'
      path: '/trading/journals'
      fullPath: '/trading/journals'
      preLoaderRoute: typeof TradingJournalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trading/Tinto': {
      id: '/trading/Tinto'
      path: '/trading/Tinto'
      fullPath: '/trading/Tinto'
      preLoaderRoute: typeof TradingTintoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orji/blogAdmin': {
      id: '/orji/blogAdmin'
      path: '/orji/blogAdmin'
      fullPath: '/orji/blogAdmin'
      preLoaderRoute: typeof OrjiBlogAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-email': {
      id: '/api/send-email'
      path: '/api/send-email'
      fullPath: '/api/send-email'
      preLoaderRoute: typeof ApiSendEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ApiSendEmailRoute: ApiSendEmailRoute,
  BlogSlugRoute: BlogSlugRoute,
  OrjiBlogAdminRoute: OrjiBlogAdminRoute,
  TradingTintoRoute: TradingTintoRoute,
  TradingJournalsRoute: TradingJournalsRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
